
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.development
    image: "parcheesi_redux.api:latest"
    ports:
      - "8383:80"
    networks:
      - shared_network
    env_file:
      - path: "./config/.parcheesi_redux.env"
        required: true
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    image: "parcheesi_redux.client:latest"
    ports:
      - "8380:80"
    networks: 
      - shared_network
      
volumes:
  teapothill_volume:
    external: true

networks:
  shared_network:
    external: true
    name: teapothill
