include:
  - db-service.yml

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.production
    image: "parcheesi_redux.api:latest"
    ports:
      - "8283:80"
    networks:
      - teapothill
    env_file:
      - path: "./config/.parcheesi_redux.env"
        required: true
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
     db:
       condition: service_healthy

volumes:
  teapothill_volume:
    external: true

networks:
  teapothill:
    external: true
