require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dee_jays", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # DeeJay. As you add validations to DeeJay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # DeeJaysController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeeJay.create! valid_attributes
      get dee_jays_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dee_jay = DeeJay.create! valid_attributes
      get dee_jay_url(dee_jay), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeeJay" do
        expect {
          post dee_jays_url,
               params: { dee_jay: valid_attributes }, headers: valid_headers, as: :json
        }.to change(DeeJay, :count).by(1)
      end

      it "renders a JSON response with the new dee_jay" do
        post dee_jays_url,
             params: { dee_jay: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeeJay" do
        expect {
          post dee_jays_url,
               params: { dee_jay: invalid_attributes }, as: :json
        }.to change(DeeJay, :count).by(0)
      end

      it "renders a JSON response with errors for the new dee_jay" do
        post dee_jays_url,
             params: { dee_jay: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dee_jay" do
        dee_jay = DeeJay.create! valid_attributes
        patch dee_jay_url(dee_jay),
              params: { dee_jay: new_attributes }, headers: valid_headers, as: :json
        dee_jay.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the dee_jay" do
        dee_jay = DeeJay.create! valid_attributes
        patch dee_jay_url(dee_jay),
              params: { dee_jay: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the dee_jay" do
        dee_jay = DeeJay.create! valid_attributes
        patch dee_jay_url(dee_jay),
              params: { dee_jay: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_content)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dee_jay" do
      dee_jay = DeeJay.create! valid_attributes
      expect {
        delete dee_jay_url(dee_jay), headers: valid_headers, as: :json
      }.to change(DeeJay, :count).by(-1)
    end
  end
end
